feat: update vault description
xpladev/_old_docs pull request #18
Opened 2022-08-20 06:31 UTC by jhlee-young

2022-08-20 09:40 UTC, caramis requested changes

2022-08-20 09:40 UTC, caramis commented on content/docs/develop/core-modules/params.md
> +`Keeper` has a permission to access all existing subspaces which are mentioned later on in this document. For example, if a proposal passes through the [governance](/docs/develop/module-specification
Could you use {{< ref "..." >}} for internal documene link ??

2022-08-20 10:01 UTC, jhlee-young commented on content/docs/develop/core-modules/params.md
> +`Keeper` has a permission to access all existing subspaces which are mentioned later on in this document. For example, if a proposal passes through the [governance](/docs/develop/module-specification
updated

2022-08-20 11:38 UTC, caramis approved these changes
LGTM

2022-08-21 11:12 UTC, psy2848048 approved these changes

2022-08-21 11:14 UTC, merged